### ISSUE TITLE
Write modular code for gradual acceleration of the robot.

### ISSUE THREAD

**Issue by omgimanerd** [stuyfission/strawberry#3]

**Comment by noobbyte** [comment]
did i not suggest this and get it shot down by you on the basis that "it is
unnecessary"

**Comment by omgimanerd** [comment]
It still is on the basis that we have a gyro now. But I want this as a template for next year.

**Comment by noobbyte** [comment]
a wat

**Comment by noobbyte** [comment]
where do you want this, for what stage of the game, using what motor configuration?

**Comment by omgimanerd** [comment]
For fx bot, we may need gradual ramping acceleration

Alvin Lin
Vice President of Stuyvesant FTC Fission 310
Head of Programming

**Comment by noobbyte** [comment]
so is this for auton or teleop or both?

**Comment by omgimanerd** [comment]
Auton

Alvin Lin
Vice President of Stuyvesant FTC Fission 310
Head of Programming
